### ISSUE TITLE
Templates support

### ISSUE THREAD

**Issue by igorshapiro** [igorshapiro/quaker#4]
Make service definition DRY

``` yaml
billing:
  git: git@github.com:company/billing.git
  environment:
    NODE_ENV: development
  volumes:
  - $:/code
warehouse:
  git: git@github.com:company/warehouse.git
  environment:
    NODE_ENV: development
  volumes:
  - $:/code
```

can be simplified to:

``` yaml
templates:
  service:
    environment:
      NODE_ENV: development
    volumes:
    - $:/code    
billing:
  templates:
  - service
  git: git@github.com:company/billing.git
warehouse:
  templates:
  - service
  git: git@github.com:company/warehouse.git
```
