### ISSUE TITLE
Repository-relative volume mounts

### ISSUE THREAD

**Issue by igorshapiro** [igorshapiro/quaker#5]
Allow defining a service:

```
billing:
  git: git@github.com:company/billing.git
  volumes:
  - $/logs:/logs
```

Where `$` will be replaced by the resolved repository location
