### ISSUE TITLE
Template overrides service tags

### ISSUE THREAD

**Issue by igorshapiro** [igorshapiro/quaker#9]
Consider:

``` yaml
some_template:
  environment:
    a: 1
  tags:
    - svc
svc:
  environment:
    - b: 2
  tags:
    - svc
```

Resulting `docker-compose.yml` will be:

``` yaml
svc:
  environment:
    - a: 1
  tags:
    - svc
```

Note the `environment` is missing the original `b: 2`. Should be:

``` yaml
svc:
  environment:
    a: 1
    b: 2
  ...
```
